export const USERS = [
    { name: 'Alice Johnson', email: 'alice.johnson@example.com', profile_url: 'https://example.com/profiles/alice' },
    { name: 'Bob Smith', email: 'bob.smith@example.com', profile_url: 'https://example.com/profiles/bob' },
    { name: 'Charlie Brown', email: 'charlie.brown@example.com', profile_url: 'https://example.com/profiles/charlie' },
    { name: 'Diana Prince', email: 'diana.prince@example.com', profile_url: 'https://example.com/profiles/diana' },
    { name: 'Ethan Hunt', email: 'ethan.hunt@example.com', profile_url: 'https://example.com/profiles/ethan' },
    { name: 'Fiona Clark', email: 'fiona.clark@example.com', profile_url: 'https://example.com/profiles/fiona' },
    { name: 'George King', email: 'george.king@example.com', profile_url: 'https://example.com/profiles/george' },
    { name: 'Hannah Lee', email: 'hannah.lee@example.com', profile_url: 'https://example.com/profiles/hannah' },
    { name: 'Ian Wright', email: 'ian.wright@example.com', profile_url: 'https://example.com/profiles/ian' },
    { name: 'Jasmine Patel', email: 'jasmine.patel@example.com', profile_url: 'https://example.com/profiles/jasmine' },
    { name: 'Kyle Adams', email: 'kyle.adams@example.com', profile_url: 'https://example.com/profiles/kyle' },
    { name: 'Laura Green', email: 'laura.green@example.com', profile_url: 'https://example.com/profiles/laura' },
    { name: 'Michael Scott', email: 'michael.scott@example.com', profile_url: 'https://example.com/profiles/michael' },
    { name: 'Nina Torres', email: 'nina.torres@example.com', profile_url: 'https://example.com/profiles/nina' },
    { name: 'Oscar Diaz', email: 'oscar.diaz@example.com', profile_url: 'https://example.com/profiles/oscar' },
    { name: 'Priya Kapoor', email: 'priya.kapoor@example.com', profile_url: 'https://example.com/profiles/priya' },
    { name: 'Quinn Harris', email: 'quinn.harris@example.com', profile_url: 'https://example.com/profiles/quinn' },
    { name: 'Rachel Kim', email: 'rachel.kim@example.com', profile_url: 'https://example.com/profiles/rachel' },
    { name: 'Steve Rogers', email: 'steve.rogers@example.com', profile_url: 'https://example.com/profiles/steve' },
    { name: 'Tina Young', email: 'tina.young@example.com', profile_url: 'https://example.com/profiles/tina' },
  ];